# Generated by Django 3.2.7 on 2021-11-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cervises',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='cervises',
            name='procedure_time',
        ),
        migrations.AlterField(
            model_name='cervises',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Cervises1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eyebrow_coloring', models.TextField()),
                ('eyebrow_correction', models.TextField()),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cervises1', to='home_page.post')),
            ],
        ),
    ]
